name: Java CI with Gradle & GraalVM

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up GraalVM JDK 21
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: '21'
        distribution: 'graalvm'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        native-image-job-reports: 'true'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: Build and test with Gradle (JVM)
      run: ./gradlew build

    - name: Build GraalVM Native Image
      run: ./gradlew nativeCompile

    - name: Upload Native Image Artifact
      uses: actions/upload-artifact@v3
      with:
        name: pollo-mail-cli-linux-amd64
        path: build/native/nativeCompile/pollo-mail-cli
